name: main_app
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: 6.0.5
  get: 4.6.5
  logger: 2.0.2
  modal_bottom_sheet: 2.1.2

  library_core:
    path: ../../plugins/library_core
  module_home:
    path: ../../plugins/module_home
  module_mine:
    path: ../../plugins/module_mine
  module_market:
    path: ../../plugins/module_market
  dart_grammar:
    path: ../../plugins/dart_grammar

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0


flutter:
